---
# handlers file for foxpass-setup

- name: specific handlers for Ubuntu
  import_tasks: Ubuntu/main.yml
  when: ansible_distribution == "Ubuntu"

- name: specific handlers for CentOS
  import_tasks: Ubuntu/main.yml
  when: ansible_distribution == "CentOS"

- name: shared handlers
  import_tasks: common.yml

