galaxy_info:
  author: Bryan
  company: Foxpass

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 20.04
  - name: CentOS
    versions:
    - 8

  galaxy_tags: []

dependencies: []
  

