---
# used to check if an the server is an ec2 instance

- name: check if inside AWS
  uri:
    url: http://169.254.169.254/latest/meta-data
    timeout: 2
  failed_when: false
  register: aws_uri_check

- name: set is_aws_enviroment variable
  set_fact:
    is_aws_environment: "{{ aws_uri_check.status == 200 }}"
